import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <SessionWrapper>
        <body className={`${inter.className} dark:bg-neutral-900`}>
          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
